// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegionBot.Context;

namespace RegionBot.Migrations
{
    [DbContext(typeof(EntityContext))]
    partial class EntityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RegionBot.Model.Region", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServicebucakID")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceilID")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceilceID")
                        .HasColumnType("int");

                    b.Property<int?>("ServicekoyID")
                        .HasColumnType("int");

                    b.Property<int?>("ServicemahalleID")
                        .HasColumnType("int");

                    b.Property<int?>("bucakID")
                        .HasColumnType("int");

                    b.Property<int?>("ilID")
                        .HasColumnType("int");

                    b.Property<int?>("ilceID")
                        .HasColumnType("int");

                    b.Property<int?>("koyID")
                        .HasColumnType("int");

                    b.Property<int?>("mahalleID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Regions");
                });
#pragma warning restore 612, 618
        }
    }
}
